-- Expense enhancements
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "originalCurrency" VARCHAR(3) DEFAULT 'EUR' NOT NULL;
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "convertedEUR" DECIMAL(10,2) DEFAULT 0 NOT NULL;
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "splitType" VARCHAR(20) DEFAULT 'equal' NOT NULL;
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "participants" JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "receipt" VARCHAR(255);

-- Settlement table
CREATE TABLE IF NOT EXISTS "Settlements" (
  "id" UUID PRIMARY KEY,
  "tripId" UUID NOT NULL REFERENCES "Trips"("id") ON DELETE CASCADE,
  "from" UUID NOT NULL REFERENCES "Users"("id"),
  "to" UUID NOT NULL REFERENCES "Users"("id"),
  "amount" DECIMAL(10,2) NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
  "proofImage" VARCHAR(255),
  "paidAt" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
